[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]

[[bin]]
name = "main"
path = "src/submission.rs"
[[bin]]
name = "meta"
path = "src/metacirc.rs"
[[bin]]
name = "lifetime"
path = "src/lifetime.rs"

[features]
development = []
grading = []